Traceback (most recent call last):
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\rrabe\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def isolatedFunction(x):
    y = 2
    z = 5
    print('Local values:')
    print(x)
    print(y)
    print(z)

isolatedFunction(3)
print('Global values:')
print(x)
print(y)
print(z)
------------------

----- stdout -----
Local values:
3
2
5
Global values:
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[11], line 11[0m
[0;32m      9[0m isolatedFunction([38;5;241m3[39m)
[0;32m     10[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mGlobal values:[39m[38;5;124m'[39m)
[1;32m---> 11[0m [38;5;28mprint[39m([43mx[49m)
[0;32m     12[0m [38;5;28mprint[39m(y)
[0;32m     13[0m [38;5;28mprint[39m(z)

[1;31mNameError[0m: name 'x' is not defined

